# Generated by Django 4.0.4 on 2022-08-31 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wndrland_app', '0002_alter_subscriber_newsletter_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subscriber_newsletter',
            table=None,
        ),
    ]
