# Generated by Django 4.0.4 on 2022-08-31 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wndrland_app', '0003_alter_subscriber_newsletter_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber_newsletter',
            options={'verbose_name': 'Subscriber'},
        ),
    ]
