# Generated by Django 4.0.4 on 2022-09-14 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wndrland_app', '0004_alter_subscriber_newsletter_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videourl', models.FileField(null=True, upload_to='deploy/videos/', verbose_name='')),
            ],
        ),
        migrations.AlterModelOptions(
            name='contact_us',
            options={'verbose_name': 'Contact u'},
        ),
    ]
