# Generated by Django 4.1 on 2022-08-31 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wndrland_app', '0004_alter_subscriber_newsletter_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact_us',
            options={'verbose_name': 'Contact u'},
        ),
    ]
