# Generated by Django 4.0.4 on 2022-09-14 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wndrland_app', '0005_video_alter_contact_us_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='videourl',
            new_name='video_desktop_url',
        ),
    ]
