# Generated by Django 4.0.4 on 2022-09-14 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wndrland_app', '0007_alter_video_video_desktop_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='desktopVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(null=True, upload_to='videos')),
            ],
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
