# Generated by Django 4.0.4 on 2022-09-14 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wndrland_app', '0008_desktopvideo_delete_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_video', models.FileField(null=True, upload_to='videos')),
            ],
        ),
    ]
