# Generated by Django 4.0.4 on 2022-09-14 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wndrland_app', '0009_mobilevideo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobilevideo',
            old_name='mobile_video',
            new_name='video',
        ),
    ]
