# Generated by Django 4.0.4 on 2022-09-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wndrland_app', '0010_rename_mobile_video_mobilevideo_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desktopvideo',
            name='video',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mobilevideo',
            name='video',
            field=models.CharField(max_length=200),
        ),
    ]
