# Generated by Django 4.0.4 on 2022-09-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wndrland_app', '0011_alter_desktopvideo_video_alter_mobilevideo_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesktopMobileVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desktop_top_video', models.CharField(max_length=200)),
                ('mobile_top_video', models.CharField(max_length=200)),
                ('desktop_bottom_video', models.CharField(max_length=300)),
                ('mobile_bottom_video', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='desktopVideo',
        ),
        migrations.DeleteModel(
            name='MobileVideo',
        ),
    ]
